<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class T_salaire extends Model
{
    protected $table = 't_salaire';

    protected $primaryKey = 'id';

    public $timestamps = false;

    protected $fillable = [
        'cat',
        's_cat',
        'inddiff1',
        'inddiff2',
        'inddiff3',
        'inddiff4',
        'inddiff5',
        'inddiff6',
        'inddiff7',
        'inddiff8',
        'inddiff9',
        'inddiff10',
        'inddiff11',
        'inddiff12',
        'inddiff13',
        'inddiff14',
        'inddiff15',
        'inddiff16',
        'inddiff17',
        'inddiff18',
        'inddiff19',
        'inddiff20',
        'inddiff21',
        'inddiff22',
        'inddiff23',
        'inddiff24',
        'inddiff25',
        'inddiff26',
        'inddiff27',
        'inddiff28',
        'inddiff29',
        'inddiff30',
        'inddiff31',
        'inddiff32',
        'inddiff33',
        'inddiff34',
        'inddiff35',
        'inddiff36',
        'inddiff37',
        'inddiff38',
        'inddiff39',
        'inddiff40',
        'th1',
        'th2',
        'th3',
        'th4',
        'th5',
        'th6',
        'th7',
        'th8',
        'th9',
        'th10',
        'th11',
        'th12',
        'th13',
        'th14',
        'th15',
        'th16',
        'th17',
        'th18',
        'th19',
        'th20',
        'th21',
        'th22',
        'th23',
        'th24',
        'th25',
        'th26',
        'th27',
        'th28',
        'th29',
        'th30',
        'th31',
        'th32',
        'th33',
        'th34',
        'th35',
        'th36',
        'th37',
        'th38',
        'th39',
        'th40',
    ];
}
